# -*- coding: utf-8 -*-
"""Home work.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cs8EIdmKPaP_kjgJfvxhcU_ff03IrjKP
"""

import pandas as pd
import sqlite3
from datetime import datetime

"""# Extract"""

# โหลดข้อมูล
df_raw = pd.read_csv('retail_logs.csv')

# ตรวจสอบโครงสร้าง
df_raw.info()
df_raw.head()

"""# Transform: ทำความสะอาดข้อมูลเบื้องต้น"""

df = df_raw.copy()

# ลบข้อมูลซ้ำ (Sale_ID ซ้ำ = แถวเดิมถูกบันทึกซ้ำ)
df = df.drop_duplicates(subset='Sale_ID', keep='first')

# ตัดช่องว่างและจัดรูปแบบตัวพิมพ์ให้เป็นมาตรฐาน (กันปัญหา 'nimman' vs 'NIMMAN')
text_cols = ['Branch', 'Province', 'Region', 'Product_Name', 'Category']
for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.title()
    df[col] = df[col].replace('Nan', pd.NA)

df['Store_Code'] = df['Store_Code'].astype(str).str.strip().str.upper()

# เติม Region ที่หายไปด้วยการ lookup จาก Province (ไม่ทิ้งข้อมูล)
province_region_map = (
    df.dropna(subset=['Region'])
      .drop_duplicates(subset='Province')
      .set_index('Province')['Region']
      .to_dict()
)
df.loc[df['Region'].isna(), 'Region'] = df.loc[df['Region'].isna(), 'Province'].map(province_region_map)

# เติม Discount ที่หายไปด้วย 0 (ไม่มีส่วนลด)
df['Discount_Percent'] = df['Discount_Percent'].fillna(0.0)

# แปลง Order_Date ที่รูปแบบไม่ตรงกัน (YYYY-MM-DD, DD-Mon-YYYY, DD/MM/YYYY) ให้เป็น datetime เดียวกัน
def parse_date(value):
    value = str(value).strip()
    for fmt in ('%Y-%m-%d', '%d-%b-%Y', '%d/%m/%Y'):
        try:
            return datetime.strptime(value, fmt)
        except ValueError:
            continue
    raise ValueError(f'Unrecognized date format: {value!r}')

df['Sale_Date_clean'] = df['Sale_Date'].apply(parse_date)

"""# Transform: สร้าง dim_location"""

dim_location = df[['Store_Code', 'Branch', 'Province', 'Region']].drop_duplicates().reset_index(drop=True)
dim_location['location_id'] = dim_location.index + 1
dim_location = dim_location[['location_id', 'Store_Code', 'Branch', 'Province', 'Region']]

"""# Transform: สร้าง dim_product"""

dim_product = df[['Product_Name', 'Category']].drop_duplicates().reset_index(drop=True)
dim_product['product_id'] = dim_product.index + 1
dim_product = dim_product[['product_id', 'Product_Name', 'Category']]

"""# Transform: สร้าง dim_date และ fact_sales"""

dim_date = df[['Sale_Date_clean']].drop_duplicates().reset_index(drop=True)
dim_date = dim_date.rename(columns={'Sale_Date_clean': 'date'})
dim_date['date_id'] = dim_date.index + 1
dim_date['year'] = dim_date['date'].dt.year
dim_date['month'] = dim_date['date'].dt.month
dim_date['day'] = dim_date['date'].dt.day
dim_date['quarter'] = dim_date['date'].dt.quarter
dim_date['month_name'] = dim_date['date'].dt.strftime('%B')
dim_date['day_of_week'] = dim_date['date'].dt.strftime('%A')

# นำ surrogate key กลับเข้า fact_sales ผ่านการ join แล้วดรอปคอลัมน์ text ทิ้ง เหลือไว้แค่ Foreign Key
fact_sales = pd.merge(df, dim_location, on=['Store_Code', 'Branch', 'Province', 'Region'], how='left')
fact_sales = pd.merge(fact_sales, dim_product, on=['Product_Name', 'Category'], how='left')
fact_sales = pd.merge(fact_sales, dim_date, left_on='Sale_Date_clean', right_on='date', how='left')

fact_sales['Amount'] = (
    fact_sales['Quantity'] * fact_sales['Unit_Price'] * (1 - fact_sales['Discount_Percent'] / 100)
).round(2)

fact_sales = fact_sales[[
    'Sale_ID', 'location_id', 'product_id', 'date_id',
    'Quantity', 'Unit_Price', 'Discount_Percent', 'Amount'
]]

"""# Load: สร้าง connection และตาราง dimension"""

conn = sqlite3.connect('retail_warehouse.db')
cursor = conn.cursor()

# เปิดใช้งานการตรวจสอบ Foreign Key ตั้งแต่ก่อนสร้างตาราง
cursor.execute('PRAGMA foreign_keys = ON;')

cursor.executescript('''
DROP TABLE IF EXISTS fact_sales;
DROP TABLE IF EXISTS dim_location;
DROP TABLE IF EXISTS dim_product;
DROP TABLE IF EXISTS dim_date;

CREATE TABLE dim_location (
    location_id INTEGER PRIMARY KEY,
    Store_Code  TEXT,
    Branch      TEXT,
    Province    TEXT,
    Region      TEXT
);

CREATE TABLE dim_product (
    product_id   INTEGER PRIMARY KEY,
    Product_Name TEXT,
    Category     TEXT
);

CREATE TABLE dim_date (
    date_id     INTEGER PRIMARY KEY,
    date        TEXT,
    year        INTEGER,
    month       INTEGER,
    day         INTEGER,
    quarter     INTEGER,
    month_name  TEXT,
    day_of_week TEXT
);
''')
conn.commit()

"""# Load: สร้างตาราง fact_sales พร้อม Foreign Key อ้างอิงไปยัง dimension ทั้งหมด"""

cursor.execute('''
    CREATE TABLE IF NOT EXISTS fact_sales (
        sale_key         INTEGER PRIMARY KEY AUTOINCREMENT,
        Sale_ID          TEXT,
        location_id      INTEGER,
        product_id       INTEGER,
        date_id          INTEGER,
        Quantity         INTEGER,
        Unit_Price       REAL,
        Discount_Percent REAL,
        Amount           REAL,
        FOREIGN KEY (location_id) REFERENCES dim_location(location_id),
        FOREIGN KEY (product_id)  REFERENCES dim_product(product_id),
        FOREIGN KEY (date_id)     REFERENCES dim_date(date_id)
    )
''')
conn.commit()

"""# Load: โหลดข้อมูลเข้าตาราง"""

dim_location.rename(columns={
    'Store_Code': 'Store_Code', 'Branch': 'Branch', 'Province': 'Province', 'Region': 'Region'
}).to_sql('dim_location', con=conn, if_exists='append', index=False)

dim_product.to_sql('dim_product', con=conn, if_exists='append', index=False)

dim_date_out = dim_date.copy()
dim_date_out['date'] = dim_date_out['date'].dt.strftime('%Y-%m-%d')
dim_date_out.to_sql('dim_date', con=conn, if_exists='append', index=False)

fact_sales.to_sql('fact_sales', con=conn, if_exists='append', index=False)

conn.commit()
print('ETL Pipeline ran successfully!')

"""# VERIFICATION"""

query = '''
SELECT
    l.Region,
    ROUND(SUM(f.Amount), 2) as Total_Revenue
FROM fact_sales f
JOIN dim_location l ON f.location_id = l.location_id
GROUP BY l.Region
ORDER BY Total_Revenue DESC
LIMIT 3;
'''

result = pd.read_sql_query(query, conn)
print(result)

conn.close()